Repository olhkyle/Bpple, pull requests merged in 2023-05, with the labels that each got.

#89 [FEAT] : CommunityMain 컴포넌트 페이지로 이동 및 NotFound 페이지 추가
  client/src/App.jsx
  client/src/components/community/Comments.jsx
  client/src/components/community/PostContent.jsx
  client/src/components/community/PostItem.jsx
  client/src/components/community/index.js
  client/src/constants/categoryList.js
  client/src/hooks/useGoBack.js
  client/src/pages/CommunityMain.jsx
  client/src/pages/NotFound.jsx
  client/src/pages/index.js
  server/mock-data/users.js
Labels: Server, Style, Refactor, Feat, Fix

#91 [FEAT] : CommunityCategorySection 컴포넌트 분리 및 추상화
  client/src/components/community/Comments.jsx
  client/src/components/community/CommunityCategoryPosts.jsx
  client/src/components/community/CommunityCategorySection.jsx
Labels: Feat, Fix

#92 [FIX] : categoryQuery import 경로 수정
  client/src/components/community/CommunityCategorySection.jsx
Labels: Style, Fix

#93 [FEAT] CommunityFaq, CommunityProfile
  client/src/App.jsx
  client/src/api/posts.js
  client/src/api/profile.js
  client/src/components/common/Faq.jsx
  client/src/components/common/FaqAccordion.jsx
  client/src/components/common/index.js
  client/src/components/common/nav/CommunitySubMenu.jsx
  client/src/components/community/CommunityHeader.jsx
  client/src/components/community/RankItem.jsx
  client/src/components/profile/AvatarProfileInfo.jsx
  client/src/components/profile/UserProfile.jsx
  client/src/pages/CommunityFaq.jsx
  client/src/pages/CommunityProfile.jsx
  client/src/pages/Rank.jsx
  client/src/pages/index.js
  client/src/routes/routePaths.js
  server/mock-data/posts.js
  server/mock-data/users.js
  server/router/posts.js
  server/router/profile.js
Labels: Feat

#99 [FEAT] : RootError 컴포넌트 구현 및 router errorElement prop으로 redirect 처리 구현
  client/src/App.jsx
  client/src/components/RootError.jsx
  client/src/components/community/Comments.jsx
  client/src/components/community/CommunityCategorySection.jsx
  client/src/components/community/PostContent.jsx
  client/src/components/index.js
  client/src/loader/communityProfileLoader.js
  client/src/pages/CommunityMain.jsx
  client/src/pages/Home.jsx
  client/src/pages/SignIn.jsx
  client/src/routes/routePaths.js
  server/router/posts.js
  server/router/profile.js
Labels: Server, Refactor, Feat, Fix

#100 [FEAT] : form 디렉토리명 Form으로 변경
  client/src/components/RootError.jsx
  client/src/components/common/FaqAccordion.jsx
  client/src/components/common/form/BirthDateInput.jsx
  client/src/components/common/form/CountrySelect.jsx
  client/src/components/common/form/DuplicateCheckInput.jsx
  client/src/components/common/form/InputWrapper.jsx
  client/src/components/common/form/PhoneNumberInput.jsx
  client/src/components/common/form/index.js
  client/src/components/common/index.js
Labels: Refactor, Feat

#101 [REFAC] : loaders, queries 디렉토리명 변경
  client/src/App.jsx
  client/src/components/common/AvatarCard.jsx
  client/src/components/common/AvatarIcon.jsx
  client/src/components/common/avatar/index.js
  client/src/components/common/index.js
  client/src/components/common/nav/LoginButton.jsx
  client/src/components/community/AutoComplete.jsx
  client/src/components/community/Comment.jsx
  client/src/components/community/CommunityCategorySection.jsx
  client/src/components/community/PostContent.jsx
  client/src/components/community/PostItem.jsx
  client/src/components/community/RankItem.jsx
  client/src/components/community/SelectProductRadio.jsx
  client/src/components/profile/AvatarEditButton.jsx
  client/src/components/profile/AvatarEditModal.jsx
  client/src/components/profile/AvatarProfileInfo.jsx
  client/src/components/profile/ProfileInfo.jsx
  client/src/components/profile/UserProfile.jsx
  client/src/components/profile/UserProfileEditForm.jsx
  client/src/components/profile/index.js
  client/src/loader/communityMeLoader.js
  client/src/loader/index.js
  client/src/loader/profileLoader.js
  client/src/loaders/index.js
  client/src/loaders/myPostsLoader.js
  client/src/loaders/myProfileLoader.js
  client/src/loaders/postDetailLoader.js
  client/src/loaders/postsByCategoryLoader.js
  client/src/loaders/profileLoader.js
  client/src/loaders/rankLoader.js
  client/src/pages/CommunityMe.jsx
  client/src/pages/CommunityPost.jsx
  client/src/pages/CommunityProfile.jsx
  client/src/pages/CommunityQuestion.jsx
  client/src/pages/CommunityRank.jsx
  client/src/pages/index.js
  client/src/queries/index.js
  client/src/queries/myPostsQuery.js
  client/src/queries/myProfileQuery.js
  client/src/queries/postDetailQuery.js
  client/src/queries/postsByCategoryQuery.js
  client/src/queries/postsByNickNameQuery.js
  client/src/queries/profileByNickNameQuery.js
  client/src/queries/rankQuery.js
  client/src/query/index.js
Labels: Refactor, Fix

#109 [FEAT] : APPLE 권장답변채택 chip 구현 및 관리자 계정 추가
  client/src/components/community/AppleRecommendChip.jsx
  client/src/components/community/comment/Comment.jsx
  client/src/components/community/comment/Comments.jsx
  client/src/pages/CommunityPostDetail.jsx
  server/mock-data/users.js
  server/router/post.js
Labels: Server, Feat, Fix

#111 [FIX] Carousel 버그 수정 및 Profile loader 제거 & suspense 적용 & Skeleton 추가
  client/src/App.jsx
  client/src/components/community/posts/EmptyPostIndicator.jsx
  client/src/components/community/posts/Posts.jsx
  client/src/components/community/question/SelectProductRadio.jsx
  client/src/components/profile/MyProductList.jsx
  client/src/components/profile/MyProfile.jsx
  client/src/components/profile/ProfileEditForm.jsx
  client/src/loaders/index.js
  client/src/loaders/profileLoader.js
  client/src/pages/CommunityProfile.jsx
  client/src/pages/MyProfile.jsx
  client/src/queries/myProfileQuery.js
  client/src/queries/postsByNickNameQuery.js
  client/src/queries/profileByNickNameQuery.js
  server/mock-data/users.js
Labels: Feat

#115 [STYLE] : UI 업데이트
  client/src/components/community/AppleRecommendButton.jsx
  client/src/components/community/autoComplete/AutoCompleteItem.jsx
  client/src/components/community/comment/Comment.jsx
  server/mock-data/users.js
Labels: Server, Style, Fix

#117 [STYLE] : Comment, AppleRecommendButton 스타일 수정
  client/src/components/common/nav/CommunitySubMenu.jsx
  client/src/components/community/AppleRecommendButton.jsx
  client/src/components/community/comment/Comment.jsx
  server/mock-data/comments.js
  server/mock-data/posts.js
  server/mock-data/users.js
Labels: Server, Style, Fix

#119 [SERVER] : mock-data 업데이트
  client/src/App.jsx
  client/src/components/common/PopupModal.jsx
  client/src/components/common/nav/CommunitySubMenu.jsx
  client/src/components/common/nav/IpadSubMenu.jsx
  client/src/components/common/nav/MenuList.jsx
  client/src/components/common/nav/index.js
  client/src/components/community/CommunityHeader.jsx
  client/src/components/community/PostContent.jsx
  client/src/components/community/autoComplete/AutoComplete.jsx
  client/src/components/community/main/QuestionInfoModal.jsx
  client/src/components/community/main/RuleInfoModal.jsx
  client/src/components/community/posts/PostSection.jsx
  client/src/pages/CommunityMyPosts.jsx
  client/src/pages/Home.jsx
  client/src/pages/NotFound.jsx
  client/src/pages/PreparePage.jsx
  client/src/pages/index.js
  client/src/routes/routePaths.js
  server/mock-data/comments.js
  server/mock-data/posts.js
  server/mock-data/users.js
Labels: Server, Style, Feat

#120 [REFAC] : Real Final Refactor
  client/src/api/post.js
  client/src/components/common/CommentLoader.jsx
  client/src/components/common/index.js
  client/src/components/community/DeletePostModal.jsx
  client/src/components/community/PostContent.jsx
  client/src/components/community/index.js
  client/src/components/community/posts/PostSection.jsx
  client/src/components/community/question/QuestionForm.jsx
  client/src/components/profile/AvatarProfileInfo.jsx
  client/src/components/profile/MyProfile.jsx
  client/src/pages/CommunityPostDetail.jsx
Labels: Server, Refactor, Feat

#122 [REFAC] : style 수정 및 리팩토링
  client/src/components/auth/SignInForm.jsx
  client/src/components/auth/SignUpForm.jsx
  client/src/pages/CommunityFaq.jsx
  client/src/pages/SignIn.jsx
Labels: Style, Refactor

#124 [FEAT] 구조 변경으로 인한 path 및 file 수정
  client/src/App.jsx
  client/src/components/common/nav/CommunitySubMenu.jsx
  client/src/components/common/nav/ComputerItSubMenu.jsx
  client/src/components/common/nav/GameSubMenu.jsx
  client/src/components/common/nav/IpadSubMenu.jsx
  client/src/components/common/nav/IphoneSubMenu.jsx
  client/src/components/common/nav/MacSubMenu.jsx
  client/src/components/common/nav/MenuList.jsx
  client/src/components/common/nav/Nav.jsx
  client/src/components/common/nav/SubMenu.jsx
  client/src/components/common/nav/UserMenu.jsx
  client/src/components/common/nav/index.js
  client/src/components/community/CommunityCategorySection.jsx
  client/src/components/community/CommunityHeader.jsx
  client/src/components/community/ComputerItHeader.jsx
  client/src/components/community/DeletePostModal.jsx
  client/src/components/community/GameHeader.jsx
  client/src/components/community/PostContent.jsx
  client/src/components/community/autoComplete/AutoComplete.jsx
  client/src/components/community/autoComplete/AutoCompleteItem.jsx
  client/src/components/community/autoComplete/NothingFound.jsx
  client/src/components/community/comment/Comment.jsx
  client/src/components/community/index.js
  client/src/components/community/posts/EmptyPostIndicator.jsx
  client/src/components/community/posts/PostItem.jsx
  client/src/components/community/question/QuestionForm.jsx
  client/src/components/community/rank/RankItem.jsx
  client/src/components/profile/RegisterProductButton.jsx
  client/src/pages/Community.jsx
  client/src/pages/CommunityMain.jsx
  client/src/pages/ComputerIt.jsx
  client/src/pages/Game.jsx
  client/src/pages/Home.jsx
  client/src/pages/PreparePage.jsx
  client/src/pages/index.js
  client/src/routes/routePaths.js
Labels: Feat

#125 [FIX] PostDetail route 경로 변경
  client/src/App.jsx
Labels: Feat

#126 [Feat] PopularPosts 페이지 추가
  client/src/App.jsx
  client/src/pages/PopularPosts.jsx
  client/src/pages/index.js
  client/src/routes/routePaths.js
Labels: Feat

#127 [FEAT] : AutoComplete 관련 Firebase 함수 및 util 함수 구현
  client/firebase/comments.js
  client/firebase/posts.js
  client/firebase/utils.js
  client/src/App.jsx
  client/src/components/community/CommunityCategorySection.jsx
  client/src/components/community/autoComplete/AutoComplete.jsx
  client/src/hooks/queries/useAutoCompleteQuery.js
  client/src/pages/CommunityCategory.jsx
  client/src/pages/CommunityMain.jsx
  client/src/pages/CommunityPostDetail.jsx
Labels: Feat, Fix
