Repository olhkyle/Bpple, pull requests merged in 2023-04, with the labels that each got.

#1 Feat footer
  client/index.html
  client/public/logo-dark.svg
  client/public/logo-light.svg
  client/public/logo.svg
  client/src/components/Root.jsx
  client/src/components/common/Footer.jsx
  client/src/styles/GlobalStyle.js
Labels: Feat

#2 [FEAT] components index 페이지 추가
  client/src/components/Root.jsx
  client/src/components/common/index.js
  client/src/components/index.js
Labels: Feat

#4 [FEAT] : Popup Modal Component
  client/src/components/common/Footer.jsx
  client/src/components/common/PopupModal.jsx
  client/src/styles/GlobalStyle.js
Labels: Feat

#5 [FEAT] ProfileAvatar
  client/public/avatars/avatar-1.png
  client/public/avatars/avatar-2.png
  client/public/avatars/avatar-3.png
  client/public/avatars/avatar-4.png
  client/public/avatars/avatar-5.png
  client/src/components/profile/ProfileAvatar.jsx
  client/src/components/profile/index.js
  client/src/constants/avatars.js
Labels: Feat

#8 [FIX] : PopupModal title prop 수정
  client/src/components/common/PopupModal.jsx
Labels: Fix

#11 [STYLE] : GlobalStyle opacity-color 추가
  client/src/styles/GlobalStyle.js
Labels: Style

#12 [Feat] TextCard 컴포넌트
  client/src/components/common/Header.jsx
  client/src/components/common/TextCard.jsx
  client/src/components/common/index.js
  client/src/components/community/RuleModal.jsx
Labels: Feat

#18 [Feat] : CommunityMe 페이지
  client/src/components/Root.jsx
  client/src/components/common/Footer.jsx
  client/src/components/community/CommunityMyPosts.jsx
  client/src/components/community/CommunityPosts.jsx
  client/src/components/community/index.js
  client/src/pages/CommunityMe.jsx
  client/src/styles/GlobalStyle.js
Labels: Feat

#19 [Feat] : Community Main 페이지 컴포넌트
  client/src/App.jsx
  client/src/components/community/CommunityMain.jsx
  client/src/components/community/index.js
  client/src/pages/Community.jsx
  client/src/pages/CommunityMe.jsx
  client/src/pages/index.js
Labels: Feat

#27 [STYLE] : InfoCard 공통 컴포넌트 스타일 수정
  client/public/community/community-main.jpeg
  client/public/community/ipad-family.png
  client/public/community/iphone-family.png
  client/public/community/mbp-notebooks.png
  client/src/components/common/InfoCard.jsx
Labels: Style

#28 [STYLE] : --secondary-bg-color 추가 및 적용
  client/src/components/common/nav/SubMenu.jsx
  client/src/styles/GlobalStyle.js
Labels: Style

#29 [FEAT] Community 메인 페이지 작업
  client/public/community/community-main.jpeg
  client/public/community/community-main.png
  client/public/community/filter-content-modal.png
  client/src/components/common/Footer.jsx
  client/src/components/common/Header.jsx
  client/src/components/common/PopupModal.jsx
  client/src/components/community/AutoComplete.jsx
  client/src/components/community/CommunityMain.jsx
  client/src/components/community/CommunityMyPosts.jsx
  client/src/components/community/CommunityPosts.jsx
  client/src/components/community/FilterContentModal.jsx
  client/src/components/community/QuestionModal.jsx
  client/src/components/community/index.js
Labels: Feat

#31 [FEAT] Nav
  client/src/components/common/nav/CommunitySubMenu.jsx
  client/src/components/common/nav/LoginButton.jsx
  client/src/components/common/nav/Nav.jsx
  client/src/components/common/nav/SubMenu.jsx
  client/src/components/common/nav/ThemeButton.jsx
  client/src/components/common/nav/index.js
  client/src/hooks/useTheme.js
  client/src/recoil/atoms/userState.js
  client/src/styles/GlobalStyle.js
Labels: Feat

#34 [FEAT] Logo 컴포넌트
  client/src/components/common/Footer.jsx
  client/src/components/common/Logo.jsx
  client/src/components/common/index.js
  client/src/components/common/nav/Nav.jsx
Labels: Feat

#35 [FEAT] Signout
  client/src/api/auth.js
  client/src/components/auth/SignIn/SignInForm.jsx
  client/src/components/common/nav/LoginButton.jsx
  server/mock-data/users.js
Labels: Feat

#36 [FEAT] Profile
  client/index.html
  client/src/App.jsx
  client/src/api/profile.js
  client/src/guard/AuthenticationGuard.jsx
  client/src/pages/Profile.jsx
  server/router/auth.js
  server/router/profile.js
Labels: Feat

#37 [FEAT] : Community 메인 페이지 AutoComplete 구현 완료
  .prettierrc.json
  client/src/App.jsx
  client/src/api/posts.js
  client/src/components/common/InfoCard.jsx
  client/src/components/common/PopupModal.jsx
  client/src/components/common/index.js
  client/src/components/community/AutoComplete.jsx
  client/src/components/community/CommunityMain.jsx
  client/src/hooks/useAutoCompleteQuery.js
  server/mock-data/posts.js
  server/router/post.js
Labels: Feat

#38 [REFACTOR] : queryClient defaultOptions 설정 항목 위치 변경
  client/src/App.jsx
Labels: Refactor

#39 [FEAT] : AutoComplete data-hovered 관련 스타일 수정 및 onSubmit 이벤트 설정
  client/src/components/community/AutoComplete.jsx
Labels: Feat

#40 [STYLE] : data-hovered 관련 스타일 및 접근성 수정
  client/src/components/community/AutoComplete.jsx
Labels: Style

#43 [SERVER] : community api 및 mock-data 수정
  server/mock-data/comments.js
  server/mock-data/posts.js
  server/router/post.js
  server/router/posts.js
Labels: Server

#44 [IMAGE] : thumbnail.png 이미지 배경 제거
  client/public/products/iphone/iphone-13/thumbnail.png
  client/public/products/iphone/iphone-14-pro/thumbnail.png
  client/public/products/iphone/iphone-14/thumbnail.png
  client/public/products/iphone/iphone-se/thumbnail.jpg
  client/public/products/iphone/iphone-se/thumbnail.png
  client/src/constants/productThumbnail.js
Labels: Image

#45 [FEAT] : Community & CommunityMe 페이지 컴포넌트 Suspense UI 구현
  client/src/App.jsx
  client/src/api/auth.js
  client/src/api/posts.js
  client/src/components/common/Loader.jsx
  client/src/components/common/index.js
  client/src/components/community/AutoComplete.jsx
  client/src/components/community/CommunityMain.jsx
  client/src/components/community/CommunityMyPosts.jsx
  client/src/components/community/CommunityPosts.jsx
  client/src/components/community/CommunitySkeleton.jsx
  client/src/components/community/index.js
  client/src/pages/Community.jsx
  client/src/pages/CommunityMe.jsx
Labels: Feat

#46 [SERVER] : server mock-data 데이터 수정 및 업데이트
  server/mock-data/comments.js
  server/mock-data/posts.js
  server/mock-data/users.js
Labels: Server

#47 [FEAT] FaqAccordion 컴포넌트 완료
  client/src/App.jsx
  client/src/api/profile.js
  client/src/components/common/FaqAccordion.jsx
  client/src/components/common/index.js
  client/src/components/profile/UserProfileEditForm.jsx
  client/src/components/profile/index.js
  client/src/pages/Profile.jsx
  client/src/pages/ProfileEdit.jsx
  client/src/pages/index.js
Labels: Feat

#49 [FIX] : Suspense true 옵션 수정
  client/src/App.jsx
  client/src/components/community/CommunityMyPosts.jsx
  client/src/components/community/index.js
  client/src/hooks/useAutoCompleteQuery.js
  client/src/pages/CommunityMe.jsx
  client/src/pages/index.js
Labels: Fix

#50 [-] : CommunityPost 파일 추가
  client/src/pages/CommunityPost.jsx
Labels: Feat

#54 [FEAT] ProfileEdit
  client/src/App.jsx
  client/src/api/profile.js
  client/src/components/profile/ProfileInfo.jsx
  client/src/components/profile/UserProfileEditForm.jsx
  client/src/components/profile/avatar/AvatarButton.jsx
  client/src/components/profile/index.js
  client/src/pages/Profile.jsx
  client/src/pages/ProfileEdit.jsx
  server/mock-data/users.js
  server/router/profile.js
  server/test/auth.rest
Labels: Feat

#57 [STYLE] : 스타일 컨벤션 통일
  client/src/components/Root.jsx
  client/src/components/common/Card.jsx
  client/src/components/common/Footer.jsx
  client/src/components/common/Form/BirthDateInput.jsx
  client/src/components/common/InfoCard.jsx
  client/src/components/common/Loader.jsx
  client/src/components/common/ScrollToTopButton.jsx
  client/src/components/common/Toast.jsx
  client/src/components/community/AutoComplete.jsx
  client/src/components/community/CommunityMain.jsx
  client/src/components/community/CommunityMyPosts.jsx
  client/src/components/profile/avatar/AvatarButton.jsx
Labels: Style

#58 [FEAT] : Apple 권장 답변, 해결된 | 해결되지 않는 질문 아이콘 컴포넌트 추가
  client/src/components/common/index.js
  client/src/components/community/AppleRecommendIcon.jsx
  client/src/components/community/CheckedCircleIcon.jsx
  client/src/components/community/CommunityMyPosts.jsx
  client/src/components/community/index.js
  server/mock-data/posts.js
  server/router/posts.js
Labels: Feat

#59 [FEAT] userState 전역 상태 변경
  client/index.html
  client/src/App.jsx
  client/src/components/Layout.jsx
  client/src/components/profile/ProductList.jsx
  client/src/components/profile/UserProfile.jsx
  client/src/components/profile/UserProfileEditForm.jsx
  client/src/guard/AuthenticationGuard.jsx
  client/src/utils/formattedDate.js
Labels: Feat

#62 [FIX] : 중복 변수 제거
  client/src/components/community/CommunityMain.jsx
Labels: Fix

#63 [REFACTOR] : useWindowScroll hook 사용
  client/src/components/common/ScrollToTopButton.jsx
  client/src/components/common/Toast.jsx
Labels: Style, Refactor

#65 [FIX] 버그 수정 및 path 변경
  client/src/App.jsx
  client/src/components/Layout.jsx
  client/src/components/auth/SignInForm.jsx
  client/src/components/auth/SignUpForm.jsx
  client/src/components/common/Form/BirthDateInput.jsx
  client/src/components/common/nav/CommunitySubMenu.jsx
  client/src/components/common/nav/IphoneSubMenu.jsx
  client/src/components/common/nav/LoginButton.jsx
  client/src/components/common/nav/MacSubMenu.jsx
  client/src/components/common/nav/Nav.jsx
  client/src/components/community/CommunityHeader.jsx
  client/src/components/index.js
  client/src/components/profile/ProductList.jsx
  client/src/components/profile/UserProfile.jsx
  client/src/components/profile/UserProfileEditForm.jsx
  client/src/constants/routes.js
  client/src/pages/Community.jsx
  client/src/pages/ProfileEdit.jsx
  client/src/routes/routePaths.js
  client/src/routes/routes.js
Labels: Feat

#66 [-] : FormInput 컴포넌트 제거로 export 문 제거
  client/src/components/common/index.js
Labels: Fix

#67 [FIX] Card style 오류 수정
  client/src/components/common/Card.jsx
Labels: Fix

#70 [REFAC] : PostItem 컴포넌트 구현 및 AutoComplete 비동기 처리 관련 리팩토링
  client/src/components/community/AutoComplete.jsx
  client/src/components/community/CommunityMain.jsx
  client/src/components/community/CommunityMyPosts.jsx
  client/src/components/community/PostItem.jsx
  client/src/hooks/useAutoCompleteQuery.js
  client/src/pages/Community.jsx
Labels: Refactor

#71 [-] : ProfileAvatar 컴포넌트 경로 관련 오류 수정
  client/src/components/community/PostItem.jsx
  client/src/pages/CommunityPost.jsx
  client/src/routes/routePaths.js
Labels: Fix

#73 [FEAT] Rank 페이지
  client/src/App.jsx
  client/src/api/rank.js
  client/src/components/community/RankItem.jsx
  client/src/components/community/RankTable.jsx
  client/src/components/community/index.js
  client/src/pages/Rank.jsx
  client/src/pages/index.js
  server/mock-data/users.js
  server/router/profile.js
  server/router/rank.js
Labels: Feat

#77 [FEAT] Register Product
  client/src/App.jsx
  client/src/api/profile.js
  client/src/components/common/avatar/AvatarEditModal.jsx
  client/src/components/common/index.js
  client/src/components/common/nav/LoginButton.jsx
  client/src/components/common/selectProduct/SelectProduct.jsx
  client/src/components/common/selectProduct/SelectProductAccordion.jsx
  client/src/components/common/selectProduct/SelectProductAccordionPanel.jsx
  client/src/components/common/selectProduct/SelectedProduct.jsx
  client/src/components/common/selectProduct/index.js
  client/src/components/profile/ProductList.jsx
  client/src/components/profile/RegisterProductButton.jsx
  client/src/components/profile/UserProfile.jsx
  client/src/components/profile/index.js
  client/src/pages/RegisterProduct.jsx
  client/src/pages/index.js
  client/src/routes/routePaths.js
  client/src/routes/routes.js
  server/mock-data/users.js
  server/router/profile.js
Labels: Feat

#81 [STYLE] : Question, Comments 페이지 컴포넌트 스타일 수정 및 CommunityCategory 페이지 이미지 width 수정
  client/src/components/common/selectProduct/SelectProductAccordion.jsx
  client/src/components/common/selectProduct/SelectProductAccordionPanel.jsx
  client/src/components/community/CategoryRadio.jsx
  client/src/components/community/Comments.jsx
  client/src/components/community/FilterContentModal.jsx
  client/src/components/community/MyProductListPanel.jsx
  client/src/components/community/QuestionForm.jsx
  client/src/components/community/RuleModal.jsx
  client/src/components/community/SelectProductRadio.jsx
  client/src/components/community/SelectedCategoryAndProductType.jsx
  client/src/pages/CommunityCategory.jsx
Labels: Style

#82 [FEAT] Rank 다크테마 적용 / Question 페이지 수정
  client/src/App.jsx
  client/src/components/common/selectProduct/SelectedProduct.jsx
  client/src/components/community/RankTable.jsx
  client/src/components/community/SelectProductRadio.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Rank.jsx
Labels: Feat

#83 [FEAT] 프로필 수정 AvatarEditModal - Radio로 변경
  client/src/components/common/avatar/AvatarEditModal.jsx
  client/src/components/profile/UserProfileEditForm.jsx
  server/router/profile.js
Labels: Feat

#84 [FEAT] : productType 데이터 추가로 Badge UI 추가 및 캐시된 데이터 fetch 방법 수정
  client/src/api/posts.js
  client/src/components/community/Comment.jsx
  client/src/components/community/Comments.jsx
  client/src/components/community/CommunityMyPosts.jsx
  client/src/components/community/PostItem.jsx
  client/src/components/community/UsefulCommentChip.jsx
  client/src/components/profile/RegisterProductButton.jsx
  client/src/components/profile/UserProfile.jsx
  client/src/components/profile/UserProfileEditForm.jsx
  client/src/hooks/queries/useAutoCompleteQuery.js
  client/src/pages/CommunityMe.jsx
  client/src/pages/CommunityPost.jsx
  server/mock-data/comments.js
  server/mock-data/posts.js
  server/mock-data/users.js
  server/router/posts.js
Labels: Server, Style, Refactor, Feat

#85 [REFAC] : SideFilter 컴포넌트 UI 및 렌더링 방법 리팩토링 및 CommunityCategory 페이지 컴포넌트 분리
  client/src/components/community/CommunityCategorySection.jsx
  client/src/components/community/CommunityMyPosts.jsx
  client/src/components/community/EmptyPostIndicator.jsx
  client/src/components/community/PostContent.jsx
  client/src/components/community/PostItem.jsx
  client/src/components/community/SideFilter.jsx
  client/src/components/community/index.js
  client/src/pages/CommunityCategory.jsx
  client/src/pages/CommunityPost.jsx
Labels: Refactor, Feat
